#!/bin/bash
if [ ! -f out/out.out ]; then
  mkdir out
  echo "This is your output folder." >> out/out.out
fi
if [ ! -f results/res.txt ]; then
  mkdir results
  echo "This is your results folder." >> results/res.txt
fi
if [ -f src/SU$1.java ]; then
  if [ -f srcSU$1.class ]; then
    rm src/SU$1.class
  fi
  
  if javac src/SU$1.java > /dev/null ; then 
    echo "--------------------------------------------------------------------"
  else
    echo "--------------------------------------------------------------------"
    echo "Compilation error, the test cases will not run."
    echo "--------------------------------------------------------------------"
    exit
  fi
else
  echo "Please put your SU$1.java file in the src folder or make sure your student number is correct"
  exit
fi
cd src
echo "Running Normal Tests"
echo "--------------------------------------------------------------------"
count=0
fail=""

for TEST_NUM in {0..20}; do
      timeout 0.05m java SU$1 T < ../test_files/test${TEST_NUM}.in > ../out/out${TEST_NUM}.out
      if diff -bB ../out/out${TEST_NUM}.out ../test_files/test${TEST_NUM}.txt > /dev/null ; then 
      echo ">>>> Passed test ${TEST_NUM} :-D" 
      count=$((count+1))
      else
        fail="$fail$TEST_NUM;"
      echo ">>>> ERROR Test Case ${TEST_NUM} failed!" 
      diff -bB ../test_files/test${TEST_NUM}.txt ../out/out${TEST_NUM}.out > ../results/diff${TEST_NUM}.out
      echo
      echo "Test case description"
      cat ../test_files/test${TEST_NUM}.ifo
      echo
      fi
    done;

echo "----------------------------------------------------------------------"
echo "Secret Normal Tests"
echo "----------------------------------------------------------------------"

for TEST_NUM in {21..39}; do
  if [ -f ../secret_test_files/test${TEST_NUM}.txt ]; then
      timeout 0.05m java SU$1 T < ../secret_test_files/test${TEST_NUM}.in > ../out/out${TEST_NUM}.out
      if diff -bB ../out/out${TEST_NUM}.out ../secret_test_files/test${TEST_NUM}.txt > /dev/null ; then 
      echo ">>>> Passed test ${TEST_NUM} :-D"
      count=$((count+1))
      else
        fail="$fail$TEST_NUM;"
      echo ">>>> ERROR Test Case ${TEST_NUM} failed!"
      diff -bB ../secret_test_files/test${TEST_NUM}.txt ../out/out${TEST_NUM}.out > ../results/diff${TEST_NUM}.out
      echo
      echo "Test case description"
      cat ../secret_test_files/test${TEST_NUM}.ifo
      echo       
      fi
  else
    echo "Still need to write test ${TEST_NUM}"
  fi
done;

echo "--------------------------------------------------------------------"
echo "Running Obstacle Tests"
echo "--------------------------------------------------------------------"

for TEST_NUM in {1..21}; do
      timeout 0.2m java SU$1 T < ../obstacle_test/obs_test${TEST_NUM}.in > ../out/obs_out${TEST_NUM}.out
      if diff -bB ../out/obs_out${TEST_NUM}.out ../obstacle_test/obs_test${TEST_NUM}.txt > /dev/null ; then 
      echo ">>>> Passed obstacle test ${TEST_NUM} :-D"
      count=$((count+1))
      else
      echo ">>>> ERROR Obstacle Test Case ${TEST_NUM} failed!" 
      diff -bB ../obstacle_test/obs_test${TEST_NUM}.txt ../out/obs_out${TEST_NUM}.out > ../results/obs_diff${TEST_NUM}.out
      echo
      echo "Test case description"
      cat ../obstacle_test/obs_test${TEST_NUM}.ifo
      echo
      fi
    done;



# echo "----------------------------------------------------------------------"
# echo "Secret Obs Tests"
# echo "----------------------------------------------------------------------"

# for TEST_NUM in {22..40}; do
#   if [ -f ../secret_obstacle_test/obs_test${TEST_NUM}.txt ]; then
#       timeout 0.2m java SU$1 T < ../secret_obstacle_test/obs_test${TEST_NUM}.in > ../out/secret_obs_out${TEST_NUM}.out
#       if diff ../out/secret_obs_out${TEST_NUM}.out ../secret_obstacle_test/obs_test${TEST_NUM}.txt > /dev/null ; then 
#       echo ">>>> Passed obstacle test ${TEST_NUM} :-D"
#       count=$((count+1))
#       else
#       echo ">>>> ERROR Obstacle Test Case ${TEST_NUM} failed!" 
#       diff ../secret_obstacle_test/obs_test${TEST_NUM}.txt ../out/obs_out${TEST_NUM}.out > ../results/obs_diff${TEST_NUM}.out
#       echo
#       echo "Test case description"
#       cat ../secret_obstacle_test/obs_test${TEST_NUM}.ifo
#       echo
#       fi
#   else
#     echo "Still need to write obstacle test ${TEST_NUM}"
#   fi
# done;

echo $count " passed"
echo "Failed: "
echo $fail